### ISSUE TITLE
Need fr.yml

### ISSUE THREAD

**Issue by HLFH** [FriendsOfFlarum/transliterator#2]
A reminder for myself and others to translate this extension to French.

**Comment by luceos** [comment]
This is not a responsibility of the maintainers. And filing reminders on repositories for yourself isn't really helping. Feel free to PR though, we'll gladly review and merge.

**Comment by HLFH** [comment]
This extension was displaying badly in French as the locale was not provided. As French is an international language, I would have expected to have this extension also in French. If people were spotting quickly on the issues board that it needs French translation, they would have translated. I see a lot of other repos elsewhere where people open issues to say they are keen to contribute to the translations, and in a second stage, they submit PRs. It seems here it is not the case.

**Comment by luceos** [comment]
It does't make sense would we create issues for all languages that are not represented or have missing translations for all extensions we maintain.

It's also starting to become more of a standard for translations to be contained inside a language pack, instead of inside the extensions. Maintainers of packages don't know all languages to review new or changed translations accurately, whereas translation extensions do.

Thanks for your understanding and commitment to consider contributing.

**Comment by dsevillamartin** [comment]
Having all the translations in it's own language pack also allows the extension maintainer(s) to not have to focus on updating the old locale, as that job falls into the language pack's maintainer, lifting weight off the extension developers.

This way they can focus on the important features rather than making sure the strings are properly translated.

**Comment by HLFH** [comment]
@luceos @datitisev Done. https://github.com/FriendsOfFlarum/transliterator/pull/3
